spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt-db
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: e3a3e7152969f160b545
            client-secret: 7537e9b3d0c0d5fa0a2f7a15b477da8ef1bc943b
